language: go

go:
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get github.com/stretchr/testify/assert

script:
  - go build
#  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
